function Hd = lpbutw_order3_cf20(Fs)
%LPBUTW_ORDER3_CF20 Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.11 and Signal Processing Toolbox 8.7.
% Generated on: 09-Jun-2022 20:28:16

% Butterworth Lowpass filter designed using FDESIGN.LOWPASS.

% All frequency values are in Hz.
%Fs = 50;  % Sampling Frequency

N  = 3;   % Order
Fc = 20;  % Cutoff Frequency

% Construct an FDESIGN object and call its BUTTER method.
h  = fdesign.lowpass('N,F3dB', N, Fc, Fs);
Hd = design(h, 'butter');

% [EOF]
